### ISSUE TITLE
Subexpression in rendr Handlebars?

### ISSUE THREAD

**Issue by dimavricos** [rendrjs/rendr-handlebars#39]
Hi!!
i am trying to do something like this:

{{  view "news/images"  lazy="true" collection_name="images" param_name="title" 
param_value="{{models.0.title}}"   }}

but {{models.0.title}}  remains when i render the view.
Is there a way to make {{models.0.title}} also dynamic?
Thank you very much!!

**Comment by jordanfbrown** [comment]
Have you tried removing the quotations?

 `param_value={{models.0.title}}` or `param_value={{models.0.attributes.title}}`

**Comment by dimavricos** [comment]
Thanks for your response!
I have tried this but the app crashes during compiling. 
Error message = Parse error on line 7 param_value={{models.0.title}} 
Expecting "string" , 'integer' 'boolean' ...
I have found this : http://stackoverflow.com/questions/14781916/is-it-possible-with-handlebars-to-nested-helpers-inside-the-options-hash
but i cant make it work.
Any other thoughts?
Thanks again!!

**Comment by jordanfbrown** [comment]
How about `param_value={{models.[0].title}}`?

**Comment by dimavricos** [comment]
Hi this didn work but i found the solution.
i had to replace {{models.0.title}} with this.models.0.title
like this
{{view "news/images"  lazy="true" collection_name="images" param_name="title" 
param_value=this.models.0.title }}

Now it works fine
Thank you very much for you time!!!

**Comment by saponifi3d** [comment]
there have been issues around this if you have multiple expressions as well - that should be fixed with rendr-handlebars@1.0.0
