### ISSUE TITLE
Confusion about peer depedency

### ISSUE THREAD

**Issue by crwang** [rendrjs/rendr-handlebars#55]
Hello,

With the current latest version 2.0.0, I'm getting: `peerinvalid Peer rendr-handlebars@2.0.0 wants rendr@>=1.2.0`

I know that there's awareness of this given the most recent commit since the latest version release, but this is a breaking issue.  Would it make sense to put out 2.0.1 with the latest commit so things don't break ?  (I'm trying to load the latest rendr-examples and I can't `npm install` if I use the current setup in the examples.

**Comment by crwang** [comment]
Actually, let me double check this I may have made a mistake.

**Comment by saponifi3d** [comment]
@crwang yeah, i noticed that i accidentally put 1.2.0 on rendr instead of 1.1.1 *doh* i've been meaning to release a fix, but i'm a bit swamped. I'll try to take care of it tonight. otherwise you can just update the peer dependency manually in the package.json for now to move foward.

**Comment by saponifi3d** [comment]
Released 2.0.1 to fix this issue.
